# Generated by Django 5.2.6 on 2025-09-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ferrari_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_name', models.CharField(max_length=20)),
                ('Model_no', models.IntegerField()),
                ('Car_number_plate', models.EmailField(max_length=254)),
                ('Date_of_Buy', models.DateField()),
                ('Cost', models.FloatField()),
            ],
        ),
    ]
