# Generated by Django 5.2.6 on 2025-09-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferrari_db',
            old_name='Car_number_plate',
            new_name='Email',
        ),
    ]
